server:
  port: 80  # 默认端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: demoApp
  # 需要将其设置为always，彩色打印日志
  output:
    ansi:
      enabled: always #彩色日志
  boot:
    admin:
      client:
        url: http://localhost:6288
        instance:
          service-url: http://localhost:8080
  # security:
  #   user:
  #     name: admin
  #     password: 123456
  datasource:  # 配置mysql
    url: ${DATASOURCE_ADDRESS}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  sql:
    init: 
      schema-locations:
      - classpath:db/userSchema.sql
      data-locations:
      - classpath:db/userData.sql
      mode: never #可能不适于mysql
  data:
    redis:
      host: 114.116.254.100
      port: 6379
      password: 112358&TonBi!
  thymeleaf:
    prefix: classpath:/templates/ #视图前缀
    suffix: .html                 #视图后缀
    encoding: UTF-8               #编码
    cache: false                  #缓存(默认开启，开发时建议关闭)
# 以上关于thymeleaf的这些参数其实都无需设置，因为都默认设置好了。参考：ThymeleafProperties
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  kafka:
    bootstrap-servers: 114.116.254.100:9092 #node1:9092,node2:9092,node3:9092 #Kafka集群
    producer:    #生产者配置
      retries: 0
      acks: 1    # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      batch-size: 16384 # 批量大小
      properties:
        linger:
          ms: 0   # 提交延时 当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka   linger.ms为0表示每接收到一条消息就提交给kafka,这时候batch-size其实就没用了
      buffer-memory: 33554432 # 生产端缓冲区大小
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #Kafka提供的序列化
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #Kafka提供的反序列化类
    consumer:
      properties:
        group:
          id: defaultConsumerGroup # 默认的消费组ID
        session:
          timeout:
            ms: 120000 # 消费会话超时时间(超过这个时间consumer没有发送心跳,就会触发rebalance操作)
        request:
          timeout:
            ms: 180000 # 消费请求超时时间
      enable-auto-commit: true # 是否自动提交offset
      auto-offset-reset: latest # 当kafka中没有初始offset或offset超出范围时将自动重置offset 参数值earliest:重置为分区中最小的offset; latest:重置为分区中最新的offset(消费分区中新产生的数据); none:只要有一个分区不存在已提交的offset,就抛出异常;
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer #Kafka提供的序列化
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer #Kafka提供的反序列化类
      auto-commit-interval: 1000ms # 提交offset延时(接收到消息后多久提交offset)

logging:
  file:
    name: logs/demoApp.file.log
snowflake:
  datacenterId: 1
  user:
    workId: 1
  group:
    workId: 2

