spring:
  profiles:
    active: log.yml
  # 需要将其设置为always，彩色打印日志
  output:
    ansi:
      enabled: always #彩色日志
  datasource:  # 配置mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.116.254.100:3306
    username: outer
    password: 123456
  sql:
    init: 
      schema-locations:
      - classpath:db/userSchema.sql
      data-locations:
      - classpath:db/userData.sql
      mode: never #可能不适于mysql
  #data:
  #  redis:
  #    host: 114.116.254.100
  #    port: 6379
  #    password: 112358&TonBi!
  thymeleaf:
    prefix: classpath:/templates/ #视图前缀
    suffix: .html                 #视图后缀
    encoding: UTF-8               #编码
    cache: false                  #缓存(默认开启，开发时建议关闭)
# 以上关于thymeleaf的这些参数其实都无需设置，因为都默认设置好了。参考：ThymeleafProperties
  mail:
    host: smtp.163.com
    username: kv30246@163.com
    password: HITNYKVIRNQOFHGE
server:
  port: 8080  # 默认端口

snowflake:
  datacenterId: 1
  workId: 1

